server:
  port: 8081
spring:  application:    name: data-storage-service
    description: Data Storage Service for storing data of polls-app
    upload-directory: D:\PROJETCS\anonymous-polls\uploads