spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: "config-server"
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "survey_app"
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

server:
  port: 0

app:
  storage-strategy: "file"
  uploads:
    base-dir: "${user.home}/Desktop"

management:
  endpoints:
    web:
      exposure:
        include: "*"
